events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # api
    upstream api-server {
        server 192.168.7.230:9081;
    }

    server {
        listen 80;

        # 프론트엔드 정적 파일 서빙
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        # auth api 프록시
        location /auth/ {
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE" always;
            add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization" always;

            if ($request_method = OPTIONS) {
                add_header Content-Length 0;
                add_header Content-Type text/javascript;
                return 204;
            }

            proxy_pass http://api-server/auth;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # admin api 프록시
        location /admin/api {
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE" always;
            add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization" always;

            if ($request_method = OPTIONS) {
                add_header Content-Length 0;
                add_header Content-Type text/javascript;
                return 204;
            }

            proxy_pass http://api-server/admin/api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
